name: dartapi_auth
description: >
  DartAPI Auth is a lightweight and extensible authentication package for Dart backend applications.
  It provides JWT-based authentication with Auth Middleware.
version: 0.0.4
repository: https://github.com/akashgk/dartapi_auth
homepage: https://github.com/akashgk/dartapi_auth
issue_tracker: https://github.com/akashgk/dartapi_auth/issues

environment:
  sdk: ^3.7.0

dependencies:
  shelf: ^1.4.2
  dart_jsonwebtoken: ^3.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
