name: dartapi_auth
description: >
  DartAPI Auth is a lightweight and extensible authentication package for Dart backend applications.
  It provides JWT-based authentication with secure access and refresh tokens, middleware protection, 
  and validation mechanisms. The package ensures security through issuer and audience validation, 
  expiration handling, and signature verification. Ideal for API authentication in Dart projects.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.0

dependencies:
  shelf: ^1.4.2
  dart_jsonwebtoken: ^3.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
